"use client";
import React from 'react';
import Navbar from '@/components/navbar';
import './globals.css';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <title>Blog App</title> 
        <meta name="description" content="Generated by create next app" />
      </Head>
      <body className={inter.className}>
        {children}
        <div
          style={{
            width: '200px',
            position: 'fixed',
            top: 0,
            right: 0,
            height: '100vh',
            display: 'flex',
            flexDirection: 'column',
            justifyContent: 'center',
            alignItems: 'flex-end',
          }}
        >
          <Navbar />
        </div>
      </body>
    </html>
  );
}